"""initial migration

Revision ID: c5acfe2c8d18
Revises: 
Create Date: 2025-06-04 22:45:51.307506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5acfe2c8d18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admins', schema=None) as batch_op:
        batch_op.alter_column('admin_name',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('admin_username',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('admin_password',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=64),
               nullable=False)

    with op.batch_alter_table('Coupon', schema=None) as batch_op:
        batch_op.alter_column('discount_type',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('discount_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('min_order_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    with op.batch_alter_table('Coupon_Ship', schema=None) as batch_op:
        batch_op.alter_column('discount_type',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('discount_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('min_order_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    with op.batch_alter_table('CustomerGroups', schema=None) as batch_op:
        batch_op.alter_column('group_description',
               existing_type=sa.VARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('OrderDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordersdtl_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('orders_id',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('prod_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.alter_column('coupon_code',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('couponship_code',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'Coupon', ['coupon_code'], ['coupon_code'])
        batch_op.create_foreign_key(None, 'Coupon_Ship', ['couponship_code'], ['couponship_code'])

    with op.batch_alter_table('ProductImages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('image_path')

    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_column('prod_stock')

    with op.batch_alter_table('roleAdmins', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roleAdmins', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prod_stock', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ProductImages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_column('image_data')

    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('couponship_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('coupon_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    with op.batch_alter_table('OrderDetails', schema=None) as batch_op:
        batch_op.alter_column('prod_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('orders_id',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.drop_column('ordersdtl_id')

    with op.batch_alter_table('CustomerGroups', schema=None) as batch_op:
        batch_op.alter_column('group_description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('Coupon_Ship', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('min_order_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('discount_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('discount_type',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    with op.batch_alter_table('Coupon', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('min_order_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('discount_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('discount_type',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    with op.batch_alter_table('Admins', schema=None) as batch_op:
        batch_op.alter_column('admin_password',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('admin_username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('admin_name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
